### PR TITLE
cari metadata, styles, layer tweaks

### PR DESCRIPTION
**Pull request by cgalvarino**
@kknee you gave me blurbs for WRF 1km and WRF 2km winds.  But I only see one WRF layer = CARIB_WRF_WINDS.  I have no idea which that is, but I went ahead and used the 1km blurb for it.

AM_SEAS currents and SST added.

Logo swapped out.

Updated temp and sal STYLES.  You might consider tweaking temp further since 25-30 is still pretty vanilla.
image

### CODE REVIEW

**Comment by kknee** [comment]
thanks @cgalvarino.  one of the tasks was to add the WRF2km source.  It's available from eds: as 
CARIB_WRF_2KM.  Just emailed you the details.

**Comment by cgalvarino** [comment]
@kknee Roger that.  Just added the 2km winds.  Let me know when you're ready to deploy.  There was the issue of the huge popups which I think was wxflow.  Coincidentally, wflow seems to be down.  But I think you already sent emails around about that.  A couple of times.

**Comment by kknee** [comment]
@cgalvarino is this on dev so I can test?  If so can you remind me of the URL, searched my email and couldn't find it.

**Comment by cgalvarino** [comment]
There is no dev assets site. I could spin one up with limited functionality. Or we could throw caution to the wind and push to prod.

**Comment by kknee** [comment]
throw caution to the wind, the url is not publicized anywhere.  

thanks!

**Comment by cgalvarino** [comment]
deployed

**Pull request merged**
