### PR TITLE
Cbibs

### PR DESCRIPTION
**Pull request by cgalvarino**
Not the best implementation, but it does the job.  No real error checking.

@lukecampbell knows about performance issues.

@kknee -25.24 deg F?  Brr!

cbibs

### CODE REVIEW

**Comment by cgalvarino** [comment]
units, https://gist.github.com/cgalvarino/22827be360280fd28937

dups, https://gist.github.com/cgalvarino/8c29edca4a44aa4f0f9e

**Comment by kknee** [comment]
And 500kt currents, wow.

Luke, can you check Api is providing correct units?

Sent from my iPhone

On Oct 7, 2015, at 9:42 AM, Charlton Galvarino <notifications@github.com<mailto:notifications@github.com>> wrote:

Not the best implementation, but it does the job. No real error checking.

@lukecampbellhttps://github.com/lukecampbell knows about performance issues.

@kkneehttps://github.com/kknee -25.24 deg F? Brr!

[cbibs]https://cloud.githubusercontent.com/assets/180985/10339098/a5ef81a4-6cd7-11e5-986d-a5a4b42125d9.png

---

You can view, comment on, or merge this pull request online at:

  https://github.com/asascience-open/maracoos_assets/pull/8

Commit Summary
-   cbibs positions
-   cbibs obs

File Changes
-   M .gitignorehttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-0 (1)
-   A getCBIBS.phphttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-1 (68)
-   M getObsLocations.phphttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-2 (14)
-   M graph.phphttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-3 (52)
-   A img/CBIBS.drawn.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-4 (0)
-   A img/CBIBS.hilite.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-5 (0)
-   A img/CBIBS.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-6 (0)
-   A img/CBIBS.select.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-7 (0)
-   M map.js.phphttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-8 (35)
-   A misc/big/bullet_squaregrey.hilite.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-9 (0)
-   A misc/big/bullet_squaregrey.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-10 (0)
-   A misc/big/bullet_squaregrey.select.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-11 (0)
-   A misc/big/bullet_squaregrey.trim.pnghttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-12 (0)
-   A popupCBIBS.phphttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-13 (71)
-   M util.phphttps://github.com/asascience-open/maracoos_assets/pull/8/files#diff-14 (3)

Patch Links:
-   https://github.com/asascience-open/maracoos_assets/pull/8.patch
-   https://github.com/asascience-open/maracoos_assets/pull/8.diff

—
Reply to this email directly or view it on GitHubhttps://github.com/asascience-open/maracoos_assets/pull/8.

This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.

Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: http://www.rpsgroup.com

**Comment by lukecampbell** [comment]
Yes, they are correct. The sensor is bad.

**Comment by lukecampbell** [comment]
The performance issues for one of the methods and the general database performance have been addressed. I'm slowly refactoring all of the code to be more performant. It's a slow process, so please bare with me.

**Comment by cgalvarino** [comment]
done

**Comment by kknee** [comment]
@cgalvarino we have thumbs up to go live with this, warts and all.

**Comment by cgalvarino** [comment]
OK.  I can't seem to pull back any timeseries today.  Things are timing out.  But here we go . . .

**Comment by kknee** [comment]
@cgalvarino timeseries looks okay to me now.  do you remember which station/parameter you tried?

**Pull request merged**
